### ISSUE TITLE
Add Broadcasting based layers/operators

### ISSUE THREAD

**Issue by clemens-fricke** [comp-physics/roseNNa#6]
I am currently looking into this tool and am very impressed with its apparent capability. But I am currently stuck on a problem that some of the layers/operations I use still need to be implemented. 

These have in common that they use numpy style broadcasting, as seen in the onnx docs.
https://github.com/onnx/onnx/blob/main/docs/Broadcasting.md

I would guess that that is a rather complicated problem in Fortran. Would converting the given operation into a known/implemented operation without the broadcasting be better? For example, the "MUL" operation into a "MatMul" Operation by converting the smaller array into the correct size by duplicating the needed value(s). This could be done in the preprocessing step in python.

For my specific current problem: I have the Normalization Layer from Tensorflow in my model, and this layer uses the Sub and Mul operation. 

If you have any good idea to add the broadcasting-based operations natively into this tool, I am willing to put in the time to implement this. Otherwise, I would rework my Tensorflow model so that these operations do not appear.

**Comment by sbryngelson** [comment]
We are glad to have your contributions @clemens-fricke ! If you open a pull request and the necessary tests into the CI I will merge it.

**Comment by ajaybati** [comment]
Hi @clemens-fricke I will look into this problem further and see what I can do. I will respond back as soon as possible. If you have any other questions, please feel free to ask!

**Comment by sbryngelson** [comment]
Currently being added by @ajaybati

**Comment by sbryngelson** [comment]
Closed due to inactivity.
