### ISSUE TITLE
Example case

### ISSUE THREAD

**Issue by sbryngelson** [comp-physics/roseNNa#8]
Add a meaningful example case. Say a feedforward NN that approximates a linear function and link that to a Fortran or C program that uses this NN approx.

**Comment by OsAmaro** [comment]
Hi. I've recently tried to link RoseNNa to a fortran physics code.

I was wondering if it would be possible to add a bit more documentation on how to use this library, and also a start-to-finish examples of how to run RoseNNa stand-alone (for a simple neural-network) and how to link to an existing code.

This would allow users to more easily apply RoseNNa in their own projects.

Thank you in advance.

**Comment by sbryngelson** [comment]
Hi @OsAmaro  -- I just added this as a tracking issue for myself or someone else. If you do not know how to link libraries, please have a look at items like:
* https://stackoverflow.com/questions/12054858/add-so-and-a-libraries-to-makefile
* https://stackoverflow.com/questions/38597420/how-to-add-libraries-to-a-make-file
* https://courses.cs.duke.edu/spring04/cps108/resources/makefiles/sample.html
